# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: ~/testproject

    steps:
      - run:
          name: Update Dependancies And Install Java 11
          command: |
            sudo apt-get -y update
            sudo apt install -y openjdk-11-jdk wget git
            java -version

      - run:
         name: Download And Install Gradle
         command: |
           VERSION=6.5.1
           wget https://services.gradle.org/distributions/gradle-${VERSION}-bin.zip -P /tmp
           sudo unzip -d /opt/gradle /tmp/gradle-${VERSION}-bin.zip
           su
           touch /etc/profile.d/gradle.sh
           echo -e "export GRADLE_HOME=/opt/gradle/latest\nexport PATH=${GRADLE_HOME}/bin:${PATH}" >> /etc/profile.d/gradle.sh
           source /etc/profile.d/gradle.sh
           exit
           gradle -v

      - run:
          name: Clone Code Repo
          command: |
            git clone https://github.com/Rantzur1992/java_example.git

      - run:
          name: Start Docker Agent
          command: |
            cd java_example
            set -x
            docker-compose up -d
            sleep 10

      # run tests
      - run:
          name: Run Test
          command: |
            cd java_example
            gradle -PmainClass=JavaExample run
